language: node_js
node_js:
  - "0.10"
before_script:
  - npm install
  - chmod +x ./scripts/deploy.sh
script: npm run deploy
env:
  global:
    - GH_REF: github.com/derekr/drk.es.git
    - secure: LCDc9z4z7pGWCYekTLxRuwsT2vpjw/+W1pFZUt7jg+76GFsC8Ilnvt/Ujm6V4cYc0mkVTmLrUvreWAMgP8cRu7lZHcNwrGrIWnwVSVpFQGlLMNXH+c+hzLfSDFhTlPqkKOV74QMHd7By0eoZ84tSOxFH3kfAMMmT/Vsl25t2dz8=
